# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-02 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_faq_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['ordering']},
        ),
    ]
