# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-02 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20170516_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='meetup_talk',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='meetup_talk',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], default='No', max_length=100),
        ),
    ]
