# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-08 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20170614_0036'),
        ('proposals', '0005_auto_20170701_1747'),
    ]

    operations = [
    ]
